config/routes.rb
Rails.application.routes.draw do
  resources :stories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'stories/index'
  root 'stories#index'

  mount Shrine::DownloadEndpoint => "/attachments"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_uploader.rb
class ImageUploader < Shrine
  # plugins and uploading logic
end

app/models/story.rb
class Story < ApplicationRecord
  validates :title, presence: true
  validates :link, format: { with: /\A(http|https)/ }

  belongs_to :user

  include ImageUploader[:image]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Returns the current user if logged in
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  # Returns a boolean representing if the user is logged in
  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  # Method to use in a filter to ensure the user is logged in
  def authorize!
    redirect_to login_path unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  # handle the post from the login page
  def create
    # Extract the email and password from the params
    email = params[:email]
    password = params[:password]

    # Find the user by their email
    user = User.find_by(email: email)

    # If we found a user and their password checks out
    if user && user.authenticate(password)
      # Save the user_id in the session cookie
      session[:user_id] = user.id

      # logged in!
      # Redirect to the root, *OR* to whatever the main page of your app is
      # (if your root_path is your landing page...)
      redirect_to stories_path
    else
      # Nope, something went wrong
      redirect_to login_path
    end
  end

  # logout
  def destroy
    # Remove their user_id from the session
    session[:user_id] = nil
    # Redirect to the root, *OR* to whatever the main page of your app is
    # (if your root_path is your landing page...)
    redirect_to stories_path
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authorize!, except: [:index]
  # GET /stories
  def index
    @page == params[:page].to_i

    @stories = Story.all.order(created_at: :desc).page(@page).per(8)
  end

  # GET /stories/1
  def show
    @story = Story.find(params[:id])
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])

    unless @story.user == current_user
      redirect_to stories_path, notice: "Error"
      return
    end
  end

  # POST /stories
  def create
    @story = Story.new(story_params)
    @story.user = current_user

    if @story.save
      redirect_to stories_path, notice: 'Story was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /stories/1
  def update
    @story = Story.find(params[:id])

    unless @story.user != current_user
      redirect_to stories_path, notice: "Change account?"
      return
    end

    if @story.update(story_params)
      redirect_to @story, notice: 'Story was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /stories/1
  def destroy
    @story = Story.find(params[:id])

    unless @story.user == current_user
      redirect_to stories_path, notice: "Error"
      return
    end

    @story.destroy
    redirect_to stories_url, notice: 'Story was successfully deleted.'
  end

  private
    # Only allow a trusted parameter "white list" through.
  def story_params
    params.require(:story).permit(:title, :link, :email, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to stories_path
    else
      redirect_to signup_path
    end
  end
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.parent_name %>
  </title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="controller-<%= controller_name%> action-<%= action_name%>">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "#", class: "navbar-brand" do %>
          Iron News
        <% end %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to stories_path do %> |Home| <% end %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
          <p class="navbar-text">Welcome: <%= current_user.name %></p>
          <li class="active"><%= link_to new_story_path do %> |Add story| <% end %></li>
          <li class="active"><%= link_to logout_path do %> |Logout| <% end %></li>

          <% else %>
          <li class="active"><%= link_to login_path do %> |Login| <% end %></li>
          <li class="active"><%= link_to signup_path do %> |Sign up| <% end %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container iron-news-main">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
  <footer>
    <nav class="navbar navbar-inverse navbar-bottom" role="navigation">
      <div class="container">
        <div class="navbar-header">
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav text-align text-center">
            <li><%= link_to stories_path do %> Guidelines|<% end %></li>
            <li><%= link_to stories_path do %>|FAQ|<% end %></li>
            <li><%= link_to stories_path do %>|Support<% end %></li>

          </ul>
        </div>
      </div>
    </nav>
  </footer>

</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @story.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h4>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
        <%= f.label :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
  </div>
  <div class="form-group">
          <%= f.label :link, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :link, class: "form-control" %>
      </div>
      <div>
        <%= f.hidden_field :image, value: @story.cached_image_data %>
        <%= f.file_field :image %>
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      </div>
  </div>
<% end -%>

app/views/stories/edit.html.erb
<div class="page-header">
  <%= link_to stories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @story, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing story</h1>
</div>

<%= render 'form' %>

app/views/stories/index.html.erb
<div class="page-header">
  <%= link_to new_story_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Story
  <% end %>
  <h1 Listing>stories</h1>
</div>
<%= paginate @stories %>
<ul class="list-group">
  <% @stories.each.with_index do |story, index| %>
    <li class="list-group-item story-item">
      <div class="media">
        <div class="pull-left">
          <%= index + 1 %>
        </div>
        <div class="pull-right">
          <%= link_to story do %>
          <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <% end %>
          <%= link_to edit_story_path(story) do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
          <%= link_to story, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end %>
        </div>
        <% if story.image_url %>
        <div class="media-left">
          <%= image_tag(story.image_url, size: "64x64") %>
        </div>
        <%else %>
        <div class="media-left">
          <img class="media-object" src="/images/twothumbsup.jpg" width="64" height="64">
        </div>
        <% end %>
        <div class="media-body">
          <h4 class="media-heading"><%= link_to story.title, story.link %></h4>
          <span>created by <%= story.user.email %></span><span> <%= distance_of_time_in_words(Time.now.to_i - story.created_at.to_i) %></span> ago
        </div>

      </div>
    </li>
  <% end %>
</ul>

app/views/stories/new.html.erb
<div class="page-header">
  <%= link_to stories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New story</h1>
</div>

<%= render 'form' %>

app/views/stories/show.html.erb
<div class="page-header">
  <!-- <%= link_to stories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_story_path(@story), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %> -->
  <h1>Show story</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @story.title %></dd>

  <dt>Link:</dt>
  <dd><%= @story.link %></dd>

  <dt>Email:</dt>
  <dd><%= @story.email %></dd>

</dl>

app/views/users/new.html.erb
<!-- Path: app/views/users/new.html.erb -->

<div class="page-header">
  <h1>Signup!</h1>
</div>

<%= form_for(@user, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>